name: p39a
channels:
  - conda-forge
  - defaults
dependencies:
  - pycocotools
  - flask
  - flask-restx
  - opencv-python
  - pandas
  - pillow
  - requests
  - scikit-image
  - scipy
  - tabulate
  - werkzeug

